Traceback (most recent call last):
  File "/Users/harrywang/sandbox/econometrics-with-python/venv/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/harrywang/sandbox/econometrics-with-python/venv/lib/python3.7/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/harrywang/sandbox/econometrics-with-python/venv/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/harrywang/sandbox/econometrics-with-python/venv/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/harrywang/sandbox/econometrics-with-python/venv/lib/python3.7/site-packages/nbclient/client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/harrywang/sandbox/econometrics-with-python/venv/lib/python3.7/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/harrywang/sandbox/econometrics-with-python/venv/lib/python3.7/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# the probability of observing 4, 5, 6, 7 successes
sum_p = 0
for k in np.arange(4, 8):
    sum_p += binom.pmf(k, 10, 0.5)
print(sum_p)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-45148c1dc764>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0msum_p[0m [0;34m=[0m [0;36m0[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mfor[0m [0mk[0m [0;32min[0m [0mnp[0m[0;34m.[0m[0marange[0m[0;34m([0m[0;36m4[0m[0;34m,[0m [0;36m8[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0msum_p[0m [0;34m+=[0m [0mbinom[0m[0;34m.[0m[0mpmf[0m[0;34m([0m[0mk[0m[0;34m,[0m [0;36m10[0m[0;34m,[0m [0;36m0.5[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0mprint[0m[0;34m([0m[0msum_p[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'binom' is not defined
NameError: name 'binom' is not defined

